blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_page, name='about'),
    path('blog/', views.BlogPage.as_view(), name='blog'),
    path('<slug:slug>/', views.BlogPostPage.as_view(), name='blog_post'),
    path('like/<slug:slug>', views.LikeBlogPost.as_view(), name='blog_like'),
]

funny_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='blog_urls'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('music/', include('guitars.urls')),
]

guitars/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('guitars/', views.GuitarsPage.as_view(), name='guitars'),
    path('submitguitar/', views.submit_guitar, name='submit-guitar'),
    path('edit/<slug:slug>', views.edit_guitar_post, name='edit-guitar'),
    path('delete/<slug:slug>', views.delete_guitar_post, name='delete-guitar'),
    path('<slug:slug>/', views.GuitarsPagePost.as_view(), name='guitars-post'),
    path('like/<slug:slug>', views.LikeGuitarPost.as_view(), name='like-guitars'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

class BlogPost(models.Model):
    """
    BlogPost Model
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='blog_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class BlogComment(models.Model):
    """
    BlogComment Model
    """
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

guitars/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

class Guitars(models.Model):
    """
    Guitars Model
    """
    guitar_model = models.CharField(max_length=50, unique=True, null=False, blank=False)
    slug = models.SlugField(max_length=50, unique=True, null=False, blank=False)
    artist = models.ForeignKey(User, on_delete=models.CASCADE, related_name='guitars')
    description = models.TextField()
    guitar_image = CloudinaryField('image', null=False, blank=False)
    remaining_guitars = models.IntegerField(null=False, blank=False)
    price = models.IntegerField(null=False, blank=False)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='guitar_likes', blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.guitar_model

    def number_of_likes(self):
        return self.likes.count()

blog/forms.py
from .models import BlogComment
from django import forms

class CommentForm(forms.ModelForm):
    """
    Comment Form Model for CommentBlog
    """
    class Meta:
        model = BlogComment
        fields = ('body',)

guitars/forms.py
from django import forms
from .models import Guitars


class SubmitGuitarForm(forms.ModelForm):
    """
    SubmitGuitarForm Model
    """
    class Meta:
        model = Guitars
        fields = (
            'guitar_model',
            'slug',
            'description',
            'guitar_image',
            'remaining_guitars',
            'price',
        )
        labels = {
            'guitar_model': 'Guitar Model',
            'slug': 'Repeat the Guitar Model without spaces.',
            'description': 'Description',
            'guitar_image': 'Select image',
            'remaining_guitars': 'How many guitars left?',
            'price': 'Price in Euros',
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import BlogPost
from .forms import CommentForm


def home_page(request):
    return render(request, 'index.html')

def about_page(request):
    return render(request, 'about.html')

class BlogPage(generic.ListView):
    """
    Blog Page View
    """
    model = BlogPost
    queryset = BlogPost.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog.html'
    paginate_by = 6

class BlogPostPage(View):
    """
    BlogPostPage View
    """
    def get(self, request, slug, *args, **kwargs):
        queryset = BlogPost.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by('created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "blog-post.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = BlogPost.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by('created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()


        return render(
            request, 
            "blog-post.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

class LikeBlogPost(View):
    """
    LikeBlogPost View
    """
    def post(self, request, slug):
        post = get_object_or_404(BlogPost, slug=slug)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('blog_post', args=[slug]))

guitars/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Guitars
from .forms import SubmitGuitarForm


class GuitarsPage(generic.ListView):
    """
    GuitarsPage View
    """
    model = Guitars
    queryset = Guitars.objects.filter(status=1).order_by('-created_on')
    template_name = 'guitars.html'
    paginate_by = 6


def submit_guitar(request):
    if request.method == 'POST':
        submission_form = SubmitGuitarForm(request.POST, request.FILES)
        if submission_form.is_valid():
            submission_form.instance.artist = request.user
            submission_form.save()
            messages.success(
                request, "Well done! Please, wait for approval :)")
            return redirect('guitars')
        else:
            submission_form = SubmitGuitarForm()
    
    return render(
        request, 
        'submit-guitar.html', 
        {
            'submission_form': SubmitGuitarForm(),
        },  
    )

def edit_guitar_post(request, slug):
    guitars = get_object_or_404(Guitars, slug=slug)
    edit_form = SubmitGuitarForm(request.POST or None, instance=guitars)
    context = {
        'edit_form': edit_form,
        'guitars': guitars
    }

    if request.method == 'POST':
        edit_form = SubmitGuitarForm(
            request.POST, request.FILES, instance=guitars)
        if edit_form.is_valid():
            guitars = edit_form.save(commit=False)
            guitars.artist = request.user
            guitars.save()
            return redirect('guitars')
    else:
        edit_form = SubmitGuitarForm(instance=guitars)

    return render(request, 'edit-guitar.html', context)


def delete_guitar_post(request, slug):
    guitars = get_object_or_404(Guitars, slug=slug)
    guitars.delete()
    return redirect('guitars')


class GuitarsPagePost(View):
    """
    GuitarsPagePost View
    """
    def get(self, request, slug, *args, **kwargs):
        queryset = Guitars.objects.filter(status=1)
        guitars = get_object_or_404(queryset, slug=slug)
        liked = False
        if guitars.likes.filter(id=self.request.user.id).exists():
            liked = True
        
        return render(
            request, 
            "guitars-post.html",
            {
                "guitars": guitars,
                "liked": liked,
            },
        )


class LikeGuitarPost(View):
    """
    LikeGuitarPost View
    """
    def post(self, request, slug):
        guitars = get_object_or_404(Guitars, slug=slug)

        if guitars.likes.filter(id=request.user.id).exists():
            guitars.likes.remove(request.user)
        else:
            guitars.likes.add(request.user)

        return HttpResponseRedirect(reverse('guitars-post', args=[slug]))

templates/about.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="col about-pg">
    <div class="row">
        <div class="col-md-8 about-img">
            <img src="{% static 'images/about-img.jpeg' %}" alt="Guitars Blog and Shop">
        </div>
        <div class="col-md-4">
            <p>Welcome to <span class="brand">Funny</span><span class="red-o">Blog!</span>
            <br/>
                Here you will be able to find the newest blogs and the most interesting products for sale.
            </p>
            <p>
                Funny Blog collaborates with all artists who want to share their creativity, hard work and hobbies.
            </p>
            </br/>
            <p>
                If you want to see what's new happening in blog section, please access <a href="{% url 'blog' %}">blog</a> for all the latest updates.
            </p>
            <br/>
            <p>
                And if you would like to share your guitars, do not hesitate to access <a href="{% url 'guitars' %}">guitars</a> for all posts and create post possibility.
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Funny Blog</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="favicon" type="image/x-icon" href="{% static 'images/favicon/favicon.ico' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">Funny<span class="red-o">Blog</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto my-2 mb-lg-0 navbar-centre">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'guitars' %}">Guitars</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <br>
</header>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

                </button>
                </div>

                {% endfor %}
            </div>
        </div>
    </div>
    <br>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

<script src="https://kit.fontawesome.com/ae519f7a97.js" crossorigin="anonymous"></script>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Dublin, Ireland</p>
        <p class="m-0 text-center text-white">Project created for educational purposes only.</p>
        <p class="m-0 text-center text-white">Follow us: 
        <ul class="social_network">
            <li>
                <a href="https://facebook.com" target="_blank" rel="noopener" aria-label="Visit our Facebook page"><i class="fa-brands fa-facebook"></i></a>
            </li>
            <li>
                <a href="https://twitter.com" target="_blank" rel="noopener" aria-label="Visit our Twitter page"><i class="fa-brands fa-twitter"></i></a>
            </li>
            <li>
                <a href="https://instagram.com" target="_blank" rel="noopener" aria-label="Visit our Instagram page"><i class="fa-brands fa-instagram"></i></a>
            </li>
            <li>
                <a href="https://github.com/sbnn3/" target="_blank" rel="noopener" aria-label="Visit our GitHub page"><i class="fa-brands fa-github"></i></a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/sebastian-neagu/" target="_blank" rel="noopener" aria-label="Visit our LinkedIn page"><i class="fa-brands fa-linkedin"></i></a>
            </li>
            <li>
                <a href="https://www.youtube.com/" target="_blank" rel="noopener" aria-label="Visit our YouTube page"><i class="fa-brands fa-youtube"></i></a>
            </li>
        </ul>
        </p>
    </footer>
    <script>
        setTimeout(function() {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close()
        }, 3000);
    </script>
</body>

</html>

templates/blog-post.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src=" {{ post.image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'blog_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>

                                {% else %}

                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>

                                {% endif %} 

                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}

                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <br>
                    <center><button type="submit" class="btn btn-signup btn-lg">Submit</button></center>
                </form>
                    

                {% endif %}
                {% endif %}

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/blog.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for post in blogpost_list %}

            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="image-container">
                            {% if "placeholder" in post.image.url %}
                            <img class="card-img-top"
                                src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                            {% else %}
                            <img class="card-img-top" src=" {{ post.image.url }}">
                            {% endif %}
                            <div class="image-flash">
                                <p class="author">Author: {{ post.author }}</p>
                            </div>
                        </div>
                        <a href="{% url 'blog_post' post.slug %}" class="post-link">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.excerpt }}</p>
                        </a>
                        <hr />
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>
                    </div>
                </div>
            </div>    
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

templates/edit-guitar.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% load cloudinary %}

<div class="col-12 guitar-zone">
    <div class="row submission-form">
        <!--NEW GUITAR SUBMIT FIELD-->
        {% if user.is_authenticated %}
        <div class="col-sm-12">
            <div class="card mb-4">
                <div class="card-body all_guitars">
                    <h2>Edit your guitar post:</h2>
                    <hr/>
                    <form method="POST" style="margin: 1.3em;" enctype="multipart/form-data">
                        {{ edit_form | crispy }}
                        {% csrf_token %}
                        <br/>
                        <center><button type="submit" class="btn btn-signup right">Submit Changes</button></center>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/guitars-post.html
{% extends 'base.html' %} 

{% block content %}

{% load crispy_forms_tags %}

<div class="col-12 guitar-zone">
    <div class="row">
        <div class="col-sm-12">
            <div class="card mb-4">
                <div class="card-body guitar-card">
                    <h2>{{ guitars.guitar_model }}</h2>
                    <hr/>
                    <div class="image-container">
                        <img class="card-img-top" src="{{ guitars.guitar_image.url }}" alt="{{ guitars.guitar_model }}">
                        <p>Artist: <strong>{{ guitars.artist }}</strong></p>
                        <hr/>
                        <p>Remaining Guitars: <strong>{{ guitars.remaining_guitars }}</strong></p>
                        <p>Price: <strong>€{{ guitars.price }}</strong></p>
                        <hr/>
                        <p>{{ guitars.description | safe }}</p>
                        <br/>
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'like-guitars' guitars.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" name="guitars_id" value="{{ guitars.slug }}" class="btn-like"><i class="fas fa-heart"></i></button>

                                {% else %}

                                <button type="submit" name="guitars_id" value="{{ guitars.slug }}" class="btn-like"><i class="far fa-heart"></i></button>

                                {% endif %} 

                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ guitars.number_of_likes }} </span>
                        </strong>
                        {% if request.user == guitars.artist %}
                        <hr/>
                        <button onclick="location.href='{% url 'edit-guitar' guitars.slug %}'" 
                        type="button" class="btn btn-signup right">EDIT</button>
                        <button onclick="location.href='{% url 'delete-guitar' guitars.slug %}'" 
                        type="button" class="btn btn-signup right">DELETE</button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/guitars.html
{% extends 'base.html' %}

{% block content %}

<!-- GUITARS -->
    <div class="col-12 guitar-zone">
        <div class="row guitar_display new-submission">
            <!--NEW GUITAR SUBMISSION FIELD-->
            {% if user.is_authenticated %}
            <div class="col-sm-6">
                <div class="card mb-4">
                    <div class="card-body all_guitars">
                        <h2>Submit your guitar:</h2>
                        <hr/>
                        <p>You would like to share something?</p>
                        <p>Just click the below button!</p>
                        <br>
                        <button onclick="location.href='{% url 'submit-guitar' %}'" type="button" class="btn btn-signup right">SUBMIT GUITAR</button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <!--Guitar-Cards-->
    <div class="container-fluid">
        <div class="row guitar_display">
            {% for guitars in guitars_list %}
            <div class="col-md-6 col-lg-3">
                <div class="card mb-4">
                    <div class="card-body all_guitars">
                        <div class="image-container">
                            <img class="card-img-top" src="{{ guitars.guitar_image.url }}" alt="{{ guitars.guitar_model }}">
                            <div class="image-flash">
                                <p>Artist: {{ guitars.artist }}</p>
                            </div>
                        </div>
                        <a href="{% url 'guitars-post' guitars.slug %}" class="print-link">
                            <h2>{{ guitars.guitar_model }}</h2>
                        </a>
                        <hr/>
                        <p>Remaining Copies: {{ guitars.remaining_guitars }}</p>
                        <p>Price: €{{ guitars.price }}</p>
                        <p class="card-text text-muted h6"><i class="far fa-heart"> {{ guitars.number_of_likes }}</i></p>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:4 %}
        </div>
        <div class="row guitar_display">
            {% endif %}
            {% endfor %}
        </div>
    </div>

{% if is_paginated %}
<nav aria-label="Page navigation">
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
</ul>
</nav>
{% endif %}
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<!--Main Image-->
<div>
    <center><video autoplay muted loop id="background_video" aria-label="Background Video">
        <source src="https://res.cloudinary.com/sebdev1/video/upload/v1663796379/bckg_video_flifdk.mp4" type="video/mp4">
    </video></center>
</div>

{% endblock %}